---
title: "20201025-p8133_computingscratch_jsg2145"
author: "Jared Garfinkel"
date: "10/25/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
output1 = vector(mode = "list", length = 20)
for(i in 1:20) {
  output1[[i]] = bind_cols("n1_response" = i)
  output1[[i]]$x = list(seq(from = 0.01, to = 0.4, by = 0.003))
}

output1 = bind_rows(output1) %>% 
  unnest(x) %>% 
  nest(x)

goutput1 = output1 %>% 
  filter(n1_response > 5)
```


```{r}
output2 = vector(mode = "list", length = 400)
for (i in 1:20) {
  for (j in 1:20) {
    output2[[c(i, j)]] = bind_cols("n1_response" = i, "n2_response" = j)
    output2[[c(i, j)]]$x = list(seq(from = 0.01, to = 0.4, by = 0.003))
  }
  output2[[i]] = map(output2[[i]], ~bind_rows(.))
}


output2 = bind_rows(output2) %>% 
  unnest(x) %>% 
  nest(x)

goutput2 = output2 %>% 
  filter(n1_response > 5,
         (n1_response + n2_response) > 11)
```


```{r}
output3 = vector(mode = "list", length = 8000)
for (i in 1:20) {
  for (j in 1:20) {
    output3[[c(i, j)]] = bind_cols("n1_response" = i, "n2_response" = j)
    output3[[c(i, j)]]$k = list(seq(from = 1, to = 20))
    output3[[c(i, j)]]$x = list(seq(from = .01, to = 0.4, by = 0.003))
  }
  output3[[i]] = map(output3[[i]], ~bind_rows(.))
}

output3 = bind_rows(output3) %>% 
  rename("n3_response" = k) %>% 
  unnest(n3_response) %>% 
  unnest(x) %>% 
  nest(x)

goutput3 = output3 %>% 
  filter(n1_response > 5,
         (n1_response + n2_response) > 11,
         (n1_response + n2_response + n3_response) > 17)
```


```{r}
output4 = vector(mode = "list", length = 88000)
for (i in 1:20) {
  for(j in 1:20) {
    output4[[c(i, j)]] = bind_cols("n1_response" = i, "n2_response" = j)
    output4[[c(i, j)]]$k = list(seq(from = 1, to = 20))
    output4[[c(i, j)]]$l = list(seq(from = 1, to = 11))
    output4[[c(i, j)]]$x = list(seq(from = .1, to = 0.16, by = 0.003))
    output4[[c(i, j)]]$n1 = 6
    output4[[c(i, j)]]$n2 = list(seq(12, 14))
    output4[[c(i, j)]]$n3 = list(seq(18, 20))
    output4[[c(i, j)]]$n4 = 24
  }
  output4[[i]] = map(output4[[i]], ~bind_rows(.))
}

output4 = bind_rows(output4) %>% 
  rename("n3_response" = k,
         "n4_response" = l) %>%
  unnest(n3_response) %>% 
  unnest(n4_response) %>% 
  unnest(n1) %>% 
  unnest(n2) %>% 
  unnest(n3) %>% 
  unnest(n4) %>% 
  unnest(x)

goutput4 = output4 %>%
  filter(n1_response > n1-1,
         (n1_response + n2_response) > n2-1,
         (n1_response + n2_response + n3_response) > n3-1,
         (n1_response + n2_response + n3_response + n4_response) > n4-1) %>% 
  nest(x)

nrow(goutput4)
```


```{r, echo = FALSE, eval = FALSE}
# goutput2 = vector(mode = "list", length = 4)
# goutput2[[1]] = output2 %>% 
#   select(n1_response) %>% 
#   filter(n1_response > 5) %>% 
#   distinct()
# goutput2[[2]] = output2 %>% 
#   select(n1_response, n2_response) %>% 
#   filter(n1_response > 5,
#          (n1_response + n2_response) > 11) %>% 
#   distinct()
# goutput2[[3]] = output2 %>% 
#   select(n1_response, n2_response, n3_response) %>% 
#   filter(n1_response > 5,
#          (n1_response + n2_response) > 11,
#          (n1_response + n2_response + n3_response) > 17) %>% 
#   distinct()
# goutput2[[4]] = output2 %>% 
#   select(n1_response, n2_response, n3_response, n4_response) %>% 
#   filter(n1_response > 5,
#          (n1_response + n2_response) > 11,
#          (n1_response + n2_response + n3_response) > 17,
#          (n1_response + n2_response + n3_response + n4_response) > 23) %>% 
#   distinct()
  # goutput2[[i]] = output2 
  #   filter(output[[i]] > 5)
  # goutput2[[i+1]]
  #          (n1_response + n2_response) > 11,
  #          (n1_response + n2_response + n3_response) > 17,
  #          (n1_response + n2_response + n3_response + n4_response) > 23)

```

```{r}
prior1 = function(df = output1, null = 0.25, stage1n = 20, n1 = 6) {
  res = df %>% 
    unnest(data) %>% 
    mutate(pE1 = dbeta(null, n1_response/stage1n, (stage1n-n1_response)/stage1n),
           pS = dbeta(null+x, 25, 75)) %>% 
    filter(n1_response > n1-1)
  res1 = res %>%
    filter(pE1 > pS) %>%
    group_by(x) %>%
    mutate(alpha = 1 - length(x)/nrow(goutput1)) %>%
    select(x, alpha) %>%
    distinct() %>%
    filter(alpha < .2)
  return(res1)
}
```


```{r}
prior2 = function(df = output2, null = 0.25, stage1n = 20, stage2n = 40, n1 = 6, n2 = 12) {
  res = df %>% 
    unnest(data) %>% 
    mutate(pE1 = dbeta(null, n1_response/stage1n, (stage1n-n1_response)/stage1n),
           pE2 = dbeta(null, (n1_response+n2_response)/stage2n, (stage2n-n1_response-n2_response)/stage2n),
           pS = dbeta(null+x, 25, 75)) %>% 
    filter(n1_response > n1-1,
           (n1_response + n2_response) > n2-1)
  res2 = res %>%
    filter(pE2 > pS) %>%
    group_by(x) %>%
    mutate(alpha = 1 - length(x)/nrow(goutput2)) %>%
    select(x, alpha) %>%
    distinct() %>%
    filter(alpha < .2)
  return(res2)
}
```


```{r}
prior3 = function(df = output3, null = 0.25, stage1n = 20, stage2n = 40, stage3n = 60, n1 = 6, n2 = 12, n3 = 18) {
  res = df %>% 
    unnest(data) %>% 
    mutate(pE1 = dbeta(null, n1_response/stage1n, (stage1n-n1_response)/stage1n),
           pE2 = dbeta(null, (n1_response+n2_response)/stage2n, (stage2n-n1_response-n2_response)/stage2n),
           pE3 = dbeta(null, (n1_response + n2_response + n3_response)/stage3n, (stage3n-n1_response-n2_response-n3_response)/stage3n),
           pS = dbeta(null+x, 25, 75)) %>% 
    filter(n1_response > n1-1,
           (n1_response + n2_response) > n2-1,
           (n1_response + n2_response + n3_response) > n3-1)
  res3 = res %>%
    filter(pE3 > pS) %>%
    group_by(x) %>%
    mutate(alpha = 1 - length(x)/nrow(goutput3)) %>%
    select(x, alpha) %>%
    distinct() %>%
    filter(alpha < .2)
  return(res3)
}
```


```{r, cache = TRUE}
prior4 = function(df = output4, null = 0.25, stage1n = 20, stage2n = 40, stage3n = 60, stage4n = 71) {
  # res = vector(mode = "list", length = 9)
  # for (i in 1:3) {
  #   for (j in 1:3) {
  res4 = df %>% 
    mutate(pE1 = dbeta(null, n1_response/stage1n, (stage1n-n1_response)/stage1n),
           pE2 = dbeta(null, (n1_response+n2_response)/stage2n, (stage2n-n1_response-n2_response)/stage2n),
           pE3 = dbeta(null, (n1_response + n2_response + n3_response)/stage3n, (stage3n-n1_response-n2_response-n3_response)/stage3n),
           pE4 = dbeta(null, (n1_response + n2_response + n3_response + n4_response)/stage4n, (stage4n-n1_response-n2_response-n3_response-n4_response)/stage4n),
           pS = dbeta(null+x, 25, 75)) %>% 
    filter(pE1 > pS,
           pE2 > pS,
           pE3 > pS,
           pE4 > pS)
  
  response1 = res4 %>% 
    group_by(n1_response) %>% 
    summarize(nresponse = n(),
              n1 = n1,
              x = x) %>% 
    distinct()
  
  response2 = res4 %>% 
    group_by(n2_response) %>% 
    summarize(nresponse = n(),
              n1 = n1,
              n2 = n2,
              x = x) %>% 
    distinct()
  response3 = res4 %>% 
    group_by(n3_response) %>% 
    summarize(nresponse = n(),
              n1 = n1,
              n2 = n2,
              n3 = n3,
              x = x) %>% 
    distinct()
  response4 = res4 %>% 
    group_by(n4_response) %>% 
    summarize(nresponse = n(),
              n1 = n1,
              n2 = n2,
              n3 = n3,
              n4 = n4,
              x = x) %>% 
    distinct()
  # responses = cbind(response1, response2, response3, response4)
#   return(responses)
# }
    # group_by(x) %>% 
    # mutate(nx = nrow(.)) 
    # summarize(n1_response = n1_response,
    #           n2_response = n2_response,
    #           n3_response = n3_response,
    #           n4_response = n4_response,
    #           nx = nx,
    #           x = x, 
    #           n1 = n1,
    #           n2 = n2,
    #           n3 = n3,
    #           n4 = n4)
  paired_up1 = res4 %>% 
    filter(n1_response > n1-1) %>% 
    summarize(sum_n1 = n(),
              n1 = n1,
              x = x) %>% 
    distinct()
  paired_up2 = res4 %>% 
    filter((n1_response + n2_response) > n2-1) %>% 
    summarize(sum_n2 = n(),
              n1 = n1,
              n2 = n2,
              x = x) %>% 
    distinct()
  paired_up3 = res4 %>% 
    filter((n1_response + n2_response + n3_response) > n3-1) %>% 
    summarize(sum_n3 = n(),
              n1 = n1,
              n2 = n2,
              n3 = n3,
              x = x) %>% 
    distinct()
  paired_up4 = res4 %>% 
    filter((n1_response + n2_response + n3_response + n4_response) > n4-1) %>% 
    summarize(sum_n4 = n(),
              n1 = n1,
              n2 = n2,
              n3 = n3,
              n4 = n4,
              x = x) %>% 
    distinct()
  
  alpha_df1 = left_join(response1, paired_up1, by = c("n1", "x"), copy = TRUE)
  alpha_df2 = left_join(response2, paired_up2, by = c("n1", "n2", "x"), copy = TRUE)
  alpha_df3 = left_join(response3, paired_up3, by = c("n1", "n2", "n3", "x"), copy = TRUE)
  alpha_df4 = left_join(response4, paired_up4, by = c("n1", "n2", "n3", "n4", "x"), copy = TRUE)
  
  alpha_df = c(alpha_df1, alpha_df2, alpha_df3, alpha_df4)
  return(alpha_df)
}

prior4 = prior4()

str(prior4)
data.frame(prior4[6:11]) %>% 
  tibble() %>% 
  group_by(n1, n2, x) %>% 
  summarize(alpha = 1 - sum(nresponse)/sum_n2,
            x = x) %>% 
  filter(alpha < 0.2)
data.frame(prior4[1:5])
data.frame(prior4[12:18]) %>% 
  tibble() %>% 
  group_by(x) %>% 
  summarize(alpha = 1 - nresponse/sum_n3,
            x = x) %>% 
  filter(alpha < 0.2)

data.frame(prior4[19:26])
```


```{r, cache = TRUE}
# alpha1 = 1 - pull(response1, nresponse1)/pull(paired_up1, sum_n1)
  # alpha2 = 1 - pull(response2, nresponse2)/pull(paired_up2, sum_n2)
  # alpha3 = 1 - pull(response3, nresponse3)/pull(paired_up3, sum_n3)
  # alpha4 = 1 - pull(response4, nresponse4)/pull(paired_up4, sum_n4)
  # 
  # alphas = cbind(alpha1, alpha2, alpha3, alpha4)
  
  # for (i in 1:4) {
  #   outcomes[[i]] = responses[[i]] %>% 
  #     list(x = list(x),
  #            alpha1 = list(1 - nresponse/pull(paired_up1, sum_n1), n1),
  #            alpha2 = list(1 - nresponse/pull(paired_up2, sum_n2), n1, n2),
  #            alpha3 = list(1 - nresponse/pull(paired_up3, sum_n3), n1, n2, n3),
  #            alpha4 = list(1 - nresponse/pull(paired_up4, sum_n4), n1, n2, n3))
  # }
  return(outcomes)
}
  #   res[[i]] = map(res[[i]], ~bind_rows(.))
  # }
# }

#       res4 = res %>%
#         filter(pE4 > pS,
#                pE3 > pS,
#                pE2 > pS,
#                pE1 > pS)
#   return(res4)
# }
```

```{r}
prior1 = prior1()
prior2 = prior2()
prior3 = prior3()
prior4 = prior4()

prior4[[1]]

prior1
prior2
prior3
prior4 %>% 
  group_by(x) %>% 
  mutate(nx = n()) %>% 
  summarize(x = x,
            nx = nx,
            n1 = n1,
            n2 = n2,
            n3 = n3,
            n4 = n4,
            n1_response = n1_response,
            n2_response = n2_response,
            n3_response = n3_response,
            n4_response = n4_response,
            alpha = 1 - nx/nrow(goutput4)) %>% 
  filter(alpha < 0.2) %>% 
  select(x, alpha, everything()) %>% 
  arrange(x, alpha) %>% 
  distinct()
  # distinct() %>% 
  # arrange(x, alpha)

left_join(prior1, prior2, by = "x") %>% 
  left_join(prior3, by = "x") %>% 
  left_join(prior4, by = "x")
```

```{r}
#delta = 0.134, alpha = 0.164
set.seed(1)
n_sim = 10e5
x = seq(0.1, 0.199, by = .003)
dat = tibble(sums = c(sum(rbeta(n_sim, shape1 = 6.5, shape2 = 15.5) > (rbeta(n_sim, shape1 = 25, shape2 = 75) + x)) / n_sim,
                      sum(rbeta(n_sim, shape1 = 5.5, shape2 = 16.5) > (rbeta(n_sim, shape1 = 25, shape2 = 75) + x)) / n_sim,
                      sum(rbeta(n_sim, shape1 = 12.5, shape2 = 29.5) > (rbeta(n_sim, shape1 = 25, shape2 = 75) + x)) / n_sim,
                      sum(rbeta(n_sim, shape1 = 11.5, shape2 = 30.5) > (rbeta(n_sim, shape1 = 25, shape2 = 75) + x)) / n_sim,
                      sum(rbeta(n_sim, shape1 = 18.5, shape2 = 43.5) > (rbeta(n_sim, shape1 = 25, shape2 = 75) + x)) / n_sim,
                      sum(rbeta(n_sim, shape1 = 17.5, shape2 = 44.5) > (rbeta(n_sim, shape1 = 25, shape2 = 75) + x)) / n_sim,
                      sum(rbeta(n_sim, shape1 = 24.5, shape2 = 48.5) > (rbeta(n_sim, shape1 = 25, shape2 = 75) + x)) / n_sim,
                      sum(rbeta(n_sim, shape1 = 23.5, shape2 = 49.5) > (rbeta(n_sim, shape1 = 25, shape2 = 75) + x)) / n_sim))
dat
```


When pE = 0.4,

```{r}
prior1 = prior1(null = 0.4)
prior2 = prior2(null = 0.4)
prior3 = prior3(null = 0.4)
prior4 = prior4(null = 0.4)

prior1
prior2
prior3
prior4
```

```{r}
adap = function(df = "output1") {
  m = str_trunc(df, 1, side = "left", ellipsis = "")
  var = paste0("n", m, "_response")
  output1 = vector(mode = "list", length = 20)
  for(i in 1:20) {
    df[[i]] = bind_cols(var = i)
    df[[i]]$x = list(seq(from = 0.01, to = 0.4, by = 0.003))
  }
  
  df = bind_rows(df) %>% 
    unnest(x) %>% 
    nest(x)
  return(df)
}
output1 = adap()
```

```{r}
str_trunc("output1", 1, side = "left", ellipsis = "")[1]
```


```{r}
output2 = output1 %>% 
  mutate(data2 = map(data, ~adap(df = "output2")))

output2
```




```{r}
output = vector(mode = "list", length = 20)
for (i in 1:20) {
  for (j in 1:51) {
    output[[c(i, j)]] = bind_cols("n1_response" = i, "n2_response" = j)
    output[[c(i, j)]]$x = list(seq(from = 0.01, to = 0.4, by = 0.003))
  }
  output[[i]] = map(output[[i]], ~bind_rows(.))
}


output = bind_rows(output) %>% 
  unnest(x) %>% 
  nest(x)

# output %>% 
#   unnest() %>% 
#   unnest(x)
```

```{r}
goutput = output %>% 
  filter(n1_response > 5,
         n1_response + n2_response > 23)
```


```{r}
prior = function(df = output, null = 0.25, stage1n = 20, stage2n = 71, n1 = 6, n2 = 24) {
  res = df %>% 
    unnest(data) %>% 
    mutate(pE1 = dbeta(null, n1_response/stage1n, (stage1n-n1_response)/stage1n),
           pE2 = dbeta(null, (n1_response+n2_response)/stage2n, (stage2n-n1_response-n2_response)/stage2n),
           pE = pE1 * pE2,
           pS = dbeta(null+x, 25, 75)) %>% 
    filter(n1_response > n1-1,
           n1_response + n2_response > n2-1)
  
  res  = res %>% 
    filter(pE>pS) %>% 
    group_by(x) %>% 
    mutate(alpha = 1 - length(x)/nrow(goutput)) %>% 
    select(x, alpha) %>% 
    distinct() %>% 
    filter(alpha < .2)
  return(res)
}
res = prior()
```
